# Generated by Django 3.2.8 on 2021-10-25 20:23

from django.db import migrations, models
import djongo.models.fields
import redsocial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('user', models.IntegerField()),
                ('comments', djongo.models.fields.EmbeddedField(model_container=redsocial.models.Comments, null=True)),
            ],
        ),
    ]
